api:
  id: ""

http:
  host: "0.0.0.0"
  port: "8088"
  
processApi:
  customerProductsOnboarding:
    protocol: "HTTPS"
    basePath: "/mocking/api/v1/links/4b733051-c14f-46ad-8737-87676f4427e8/tenants/{tenantId}/onboardings"
    host: "anypoint.mulesoft.com"
    port: "443"
    connectionIdleTimeout: "180000"
    connectionTimeout: "10000"
    responseTimeout: "50000"
    reconnection:
      frequency: "1000"
      attempts: "2"
    auth:
      enabled: "false"
      clientId:
        headerName: "clientId"
        value: "123"
      clientSecret:
        headerName: "clientSecret"
        value: "456"
    notTransientErrorCodes: "400,401,403,404,405,406,407,408,409,412,413,414,415,422,429,500,501,508,511"
    operations:
      screeningRequests:
        path: "/{id}/screening-requests"
        method: "POST"
        maxRetries: "0"
        millisBetweenRetries: "1000"
      generateDocsFromTemplate:
        path: "/{id}/documents/.generate"
        method: "POST"
        maxRetries: "0"
        millisBetweenRetries: "1000"
      uploadDocument:
        path: "/{id}/.upload"
        method: "POST"
        maxRetries: "0"
        millisBetweenRetries: "1000"   
                
  affluentManagement:
    protocol: "HTTP"
    basePath: "/api/tenants/{tenantId}/onboardings"
    host: "localhost"
    port: "8087"
    connectionIdleTimeout: "180000"
    connectionTimeout: "10000"
    responseTimeout: "50000"
    reconnection:
      frequency: "1000"
      attempts: "2"
    auth:
      enabled: "false"
      clientId:
        headerName: "clientId"
        value: "123"
      clientSecret:
        headerName: "clientSecret"
        value: "456"
    notTransientErrorCodes: "400,401,403,404,405,406,407,408,409,412,413,414,415,422,429,500,501,508,511"
    operations:
      createCustomerProductOnboarding:
        path: ""
        method: "POST"
        maxRetries: "0"
        millisBetweenRetries: "1000" 
      sendOwnershipConfOTP:
        path: "/{id}/.send-ownership-confirmation-otp"
        method: "POST"
        maxRetries: "0"
        millisBetweenRetries: "1000" 
      validateOwnershipConfOTP:
        path: "/{id}/.validate-ownership-confirmation-otp"
        method: "POST"
        maxRetries: "0"
        millisBetweenRetries: "1000" 
      requestSignature:
        path: "/{id}/.request-signature"
        method: "POST"
        maxRetries: "0"
        millisBetweenRetries: "1000" 
      validateSignature:
        path: "/{id}/.validate-signature"
        method: "POST"
        maxRetries: "0"
        millisBetweenRetries: "1000" 

##Sobrescreve as configs do .operations          
api-call:
  postOnboarding:
    affluentManagement: 
      createCustomerProductOnboarding:
        maxRetries: "0"
        millisBetweenRetries: "1000"
  postScreeningRequests:
    customerProductsOnboarding: 
      screeningRequests:
        maxRetries: "0"
        millisBetweenRetries: "1000"
  postPPEScreeningRequests:
    customerProductsOnboarding: 
      screeningRequests:
        maxRetries: "0"
        millisBetweenRetries: "1000"  
  postSendOwnershipConfOTP:
    affluentManagement: 
      sendOwnershipConfOTP:
        maxRetries: "0"
        millisBetweenRetries: "1000" 
        validationDurationInSec: "600"
        validationMarginInSec: "60"
  postValidateOwnershipConfirmation:
    affluentManagement:
      postValidateOwnershipConfirmation:
        validationDurationInSec: "600"
        validationMarginInSec: "60"
  postW8Forms:
    customerProductsOnboarding: 
      generateDocsFromTemplate:
        maxRetries: "0"
        millisBetweenRetries: "1000"   
  postTermsAndContracts:
    customerProductsOnboarding: 
      generateDocsFromTemplate:
        maxRetries: "0"
        millisBetweenRetries: "1000"          