api:
  id: ""

http:
  host: "0.0.0.0"
  port: "8088"


##Sobrescreve as configs do .operations          
api-call:
  postOnboarding:
    affluentManagement: 
      createCustomerProductOnboarding:
        maxRetries: "0"
        millisBetweenRetries: "1000"
  postScreeningRequests:
    customerProductsOnboarding: 
      screeningRequests:
        maxRetries: "0"
        millisBetweenRetries: "1000"
  postPPEScreeningRequests:
    customerProductsOnboarding: 
      screeningRequests:
        maxRetries: "0"
        millisBetweenRetries: "1000"  
  postSendOwnershipConfOTP:
    affluentManagement: 
      sendOwnershipConfOTP:
        maxRetries: "0"
        millisBetweenRetries: "1000" 
        validationDurationInSec: "600"
        validationMarginInSec: "60"
  postValidateOwnershipConfirmation:
    affluentManagement:
      postValidateOwnershipConfirmation:
        validationDurationInSec: "600"
        validationMarginInSec: "60"
  postW8Forms:
    customerProductsOnboarding: 
      generateDocsFromTemplate:
        maxRetries: "0"
        millisBetweenRetries: "1000"            